# Generated by Django 5.0.1 on 2024-01-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='news',
            name='comments',
        ),
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
