# Generated by Django 5.0.1 on 2024-01-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_news_tags_remove_news_comments_news_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='related_url',
        ),
    ]
