# Generated by Django 5.0.1 on 2024-01-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_news_related_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default=1, upload_to='blog_media/'),
            preserve_default=False,
        ),
    ]
